## Edit
## organization_name => replace all with your github organization name with lowercase
## repository_name => replace all with your github repository name with lowercase
## hostname => replace all with your application hostname with lowercase
## path => replace all with your application path with lowercase

replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: Always

imagePullSecrets:
  - acr-secret

nameOverride: do66001-ppe-be-ppe-online-authentication-dev
fullnameOverride: do66001-ppe-be-ppe-online-authentication-dev

env:
  - name: PTT_PPE_AUTHENTICATION_API_AppId
    value: "01GWB8DB47JB3HAT6XX0TBSQBD"
    
  - name: PTT_PPE_AUTHENTICATION_API_AppName
    value: "Authorization API"
    
  - name: PTT_PPE_AUTHENTICATION_API_SymmetricKey
    value: "P@ssw0rd"
    
  - name: PTT_PPE_AUTHENTICATION_API_Authorization__JwtSecret
    value: "819C31CB-8EEF-437B-ADDC-C40FAF725ADA"
    
  - name: PTT_PPE_AUTHENTICATION_API_ClientConfigs__AccessTokenExpireInMinutes
    value: 30
    
  - name: PTT_PPE_AUTHENTICATION_API_ClientConfigs__RefreshTokenLifeTimeInMinutes
    value: 60
    
  - name: PTT_PPE_AUTHENTICATION_API_ClientConfigs__SessionTokenExpireInHour
    value: 24
    
  - name: PTT_PPE_AUTHENTICATION_API_UseInMemory
    value: false
    
  - name: PTT_PPE_AUTHENTICATION_API_ConnectionSettings__DataConnection__AppName
    value: "Authorization API"
    
  - name: PTT_PPE_AUTHENTICATION_API_ConnectionSettings__DataConnection__Host
    value: "pttgc-poc.database.windows.net"
    
  - name: PTT_PPE_AUTHENTICATION_API_ConnectionSettings__DataConnection__Port
    value: 1433
    
  - name: PTT_PPE_AUTHENTICATION_API_ConnectionSettings__DataConnection__Database
    value: "ppe"
    
  - name: PTT_PPE_AUTHENTICATION_API_ConnectionSettings__DataConnection__ConnectionTimeout
    value: 3000
    
  - name: PTT_PPE_AUTHENTICATION_API_ConnectionSettings__DataConnection__Credentials
    value: "ppe:8yGH@#4Ut2o0"
    
  - name: PTT_PPE_AUTHENTICATION_API_KeyVaultSettings__Url
    value: "https://pttgc-poc-app.vault.azure.net"
    
  - name: PTT_PPE_AUTHENTICATION_API_KeyVaultSettings__TenantId
    value: "cd01580f-b92e-494c-8b45-706ed5820613"
    
  - name: PTT_PPE_AUTHENTICATION_API_KeyVaultSettings__ClientId
    value: "dbd21da9-b7aa-4bed-aba0-281dfa6b3946"
    
  - name: PTT_PPE_AUTHENTICATION_API_KeyVaultSettings__ClientSecret
    value: "gHn8Q~LU_7sX1lMAsFAYfyNZhvFq3qmOm53M0b9Q"
    
  - name: PTT_PPE_AUTHENTICATION_API_Authentication__Schema
    value: "dev.auth"
    
  - name: PTT_PPE_AUTHENTICATION_API_Authentication__Collation
    value: "Thai_CI_AS"
    
  - name: PTT_PPE_AUTHENTICATION_API_GrapgApiUserProfile
    value: "/v1.0/me"
    
  - name: PTT_PPE_AUTHENTICATION_API_ApiClients__ApiGraph__BaseUri
    value: "https://graph.microsoft.com"
    
  - name: PTT_PPE_AUTHENTICATION_API_ApiClients__ApiPpe__BaseUri
    value: "http://localhost:5026"
    
  - name: PTT_PPE_AUTHENTICATION_API_ApiClients__ApiPpe__ApiKey
    value: "03655239-1ef0-4970-929c-1e0991cb39d2"
    
  - name: PTT_PPE_AUTHENTICATION_API_ApiClients__ApiAuth__ApiKey
    value: "d9e410b8-9326-4956-8773-0c5115f09fc0"

  - name: PTT_PPE_AUTHENTICATION_API_MinimumLevel__Override__PTTDigital
    value: "Debug"
    
  - name: PTT_PPE_AUTHENTICATION_API_TbSysPermissions
    value: "/api/v1/Ppe/TbSysPolicy/TbSysPermissions"
        
containerPorts:
  - 80

resources:
  requests:
    cpu: 500m
  limits:
    cpu: 500m

# volumeMounts:
#   - mountPath: "/data/"
#     name: file-volume-claim

# volumes:
#   - name: file-volume-claim
#     persistentVolumeClaim:
#       claimName: claim-file-pvc

nodeSelector: {}

tolerations: []

affinity: {}

service:
  enabled: true
  type: ClusterIP
  annotation: {}
  ports:
    - name: do66001-ppe-be-ppe-online-authentication-dev-svc
      protocol: TCP
      externalPort: 80
      internalPort: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/use-regex: "true"
  tls:
    - hosts:
        - ppe-authen-dev.pttdigitalpoc.com
      secretName: do66001-ppe-be-online-authen-dev-tls-secret
  hosts:
    - host: ppe-authen-dev.pttdigitalpoc.com
      paths:
        - path: /
          # - path: /path(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: do66001-ppe-be-ppe-online-authentication-dev
              port:
                number: 80
